package com.alevel.springMVC.sweater;


import com.alevel.springMVC.sweater.domain.Message;
import com.alevel.springMVC.sweater.repository.MessageRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.Map;

@Controller // This means that this class is a Controller
public class GreetingController {
    // @Controller - модуль программы, который слушает запросы по пути "/greeting" и возвращает значение "name"

    // This means to get the bean called messageRepo
    // Which is auto-generated by Spring, we will use it to handle the data

    @Autowired
    private MessageRepo messageRepo;

    // Аннотация @RequestMapping гарантирует, что HTTP запросы к /greeting приведут к выполнению метода greeting().
    // @RequestParam связывает значение строкового параметра name запроса с name параметром метода greeting().
    // Этот параметр не required; если он отсутствует в запросе, то будет использовано defaultValue значение "World".

    @GetMapping("/") // Map ONLY GET Requests

    public String greeting(Map<String, Object> model) {

        return "greeting";
    }

    @GetMapping("/main")
    // @GetMapping is a shortcut for @RequestMapping(method=GET)

    public String main(Map<String, Object> model) {
        Iterable<Message> messages = messageRepo.findAll();
        // This returns a JSON or XML with the messages

        model.put("messages", messages);

        return "main";
    }

    @PostMapping("/main")
    // @RequestParam means it is a parameter from the GET or POST request
    public String add(@RequestParam String text,
                      @RequestParam String tag,
                      Map<String, Object> model) {

        Message message = new Message(text, tag);
        messageRepo.save(message);

        Iterable<Message> messages = messageRepo.findAll();
        model.put("messages", messages);

        return "main";
    }

    @PostMapping("/filter")
    public String filter(@RequestParam String filter,
                         Map<String, Object> model) {
        Iterable<Message> messages;

        if (filter != null && !filter.isEmpty()) {
            messages = messageRepo.findByTag(filter);
        } else {
            messages = messageRepo.findAll();
        }

        model.put("messages", messages);

        return "main";
    }
}